### ISSUE TITLE
Question regarding CIFAR-100 training accuracy being Lower than evaluation accuracy

### ISSUE THREAD

**Issue by Jung-Echo** [gqk/LAE#6]
I've noticed an intriguing phenomenon where the training accuracy is lower than the evaluation accuracy. This seems to deviate from the common trend where training accuracy usually surpasses evaluation accuracy.
<img width="1083" alt="image" src="https://github.com/gqk/LAE/assets/56183446/5d885402-8386-489a-8801-39a0185f2775">

To provide some context, I have run the L2P code and observed that, as expected, the training accuracy for CIFAR-100 is higher than the evaluation accuracy. However, with your LAE method applied to the ImageNet-R dataset, it aligns well with the usual pattern of higher training accuracy. This leads me to wonder if there might be a specific reason behind the different behavior observed with CIFAR-100 in your implementation.
<img width="1083" alt="image" src="https://github.com/gqk/LAE/assets/56183446/862ff207-d336-4088-97af-5b07a2c564f1">

I am curious to understand more about this and would greatly appreciate any insights or explanations you could provide. Understanding the nuances of your approach would be incredibly beneficial for my ongoing research and experiments.

Thank you very much for your time and consideration. I am looking forward to your response.

**Comment by gqk** [comment]
Dear @Jung-Echo 

Thank you for your insightful observation. The difference in training and evaluation accuracy you noted stems from our implementation.

In our approach, during training, we only use the online PET module to make predictions, and this module is updated based on the new task. However, during the training process, we also update the offline PET module using Exponential Moving Average (EMA), though this module is not directly involved in predictions during training.

During evaluation, we use a combination of both the online PET module and the offline PET module to make predictions. This ensemble of the two results during evaluation typically results in better generalization performance, leading to higher evaluation accuracy compared to the training accuracy.

I hope this clarifies the behavior you observed. Feel free to reach out if you have any further questions!

Best regards,  

Qiankun Gao
